apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstardeploy
  labels:
    app: hotstar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstarcont
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
